.github/workflows/macos-matrix.yml: printenv & installs

diff --git a/.github/workflows/ubuntu-matrix.yml b/.github/workflows/ubuntu-matrix.yml
--- a/.github/workflows/ubuntu-matrix.yml
+++ b/.github/workflows/ubuntu-matrix.yml
@@ -1,4 +1,4 @@
-name: macos-matrix
+name: ubuntu-matrix
 
 # Controls when the action will run.
 on:
@@ -21,21 +21,29 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  macos-build_and_test:
+  ubuntu-build_and_test:
     strategy:
       matrix:
-        os: [macos-latest, macos-11, macos-12]
+        os: [ubuntu-20.04, ubuntu-latest]
     runs-on: ${{ matrix.os }}
     steps:
       - uses: styfle/cancel-workflow-action@0.9.1
         with:
           access_token: ${{ github.token }}
       - uses: actions/checkout@v2
-      - name: printenv & installs
+      - name: printenv
         run: |
           printenv
-          if hash make; then make -v; else  brew install automake; fi
-          if hash swift; then swift -version; else  brew install swift; fi
       - name: make
         run: |
-          make all
+          make
+      - name: sudo make install
+        run: |
+          sudo make install
+      - name: man nostril
+        run: |
+          man nostril
+      - name: sudo -su runner nostril
+        run: |
+          #pipe handles non-zero return from nostril default help
+          sudo -su runner nostril        | echo "${PIPESTATUS[0]}"
